### ISSUE TITLE
serialization error when a generic block is saved

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#229]
Trying to open a diagram that contains a generic block leads to 
![image](https://user-images.githubusercontent.com/67690903/149969226-83f4f51a-141e-43e6-b41d-80bb8e5e0630.png)
I am attaching the zipped project folder
[test6.zip](https://github.com/SPF-OST/pytrnsys_gui/files/7890314/test6.zip)

**Comment by martin-neugebauer** [comment]
@zuckerruebe I am wondering if we should keep the generic items.

**Comment by martin-neugebauer** [comment]
@PuaYongHao This is what you showed me.

**Comment by zuckerruebe** [comment]
@martin-neugebauer: if we don't need them we should remove them. If we need them, we should fix the bug. It would be cool to have a generic item whose ports are automatically generated from the placeholders in the ddck, though, wouldn't it? Now that we have placeholders.

**Comment by martin-neugebauer** [comment]
Well I've never used them, but there are probably occasions where they could be useful. So I support fixing the bug and automatic creation. :-)
I wouldn't put a very high priority, though.

**Comment by ahobeost** [comment]
@zuckerruebe: This problem remains.
Based on Djordje's needs, I suggest this needs to be fixed
This should then also be prioritized.
